export const dummySkills: SkillRecord[] = [
    {
        id: "cl-101",
        title: "React Query Essentials",
        description:
            "Mastering asynchronous state management and data fetching in React applications.",
        slug: "react-query-essentials",
        category: "Frontend",
        tags: ["react", "tanstack", "state-management"],
        installCommand: "npm i @tanstack/react-query",
        createdAt: "2026-05-01T10:00:00Z",
        authorClerkId: "user_2N72ax",
        authorEmail: "dev@example.com",
    },
    {
        id: "cl-102",
        title: "Tailwind UI Components",
        description:
            "A collection of accessible, reusable components built with Tailwind CSS.",
        slug: "tailwind-ui-components",
        category: "Design",
        tags: ["css", "ui", "tailwind"],
        installCommand: "npm i tailwindcss-animate",
        createdAt: "2026-05-02T14:30:00Z",
        authorClerkId: "user_8J22bz",
        authorEmail: "designer@example.com",
    },
    {
        id: "cl-103",
        title: "Drizzle ORM Setup",
        description:
            "TypeScript-first ORM for SQL databases with maximum type safety.",
        slug: "drizzle-orm-setup",
        category: "Backend",
        tags: ["database", "typescript", "orm"],
        installCommand: "npm i drizzle-orm",
        createdAt: "2026-05-03T09:15:00Z",
        authorClerkId: "user_9K33cc",
        authorEmail: "backend-lead@database.io",
    },
    {
        id: "cl-104",
        title: "Next.js Authentication",
        description:
            "Implementing secure authentication patterns using Clerk and Next.js middleware.",
        slug: "nextjs-auth-clerk",
        category: "Security",
        tags: ["auth", "nextjs", "clerk"],
        installCommand: "npm i @clerk/nextjs",
        createdAt: "2026-05-04T18:45:00Z",
        authorClerkId: "user_4K99pp",
        authorEmail: "security-lead@example.com",
    },
    {
        id: "cl-105",
        title: "TanStack Router Config",
        description:
            "Configuration for type-safe routing and file-based route generation.",
        slug: "tanstack-router-config",
        category: "Frontend",
        tags: ["routing", "typescript", "tanstack"],
        installCommand: "npm i @tanstack/react-router",
        createdAt: "2026-05-04T20:30:00Z",
        authorClerkId: "user_1A23cc",
        authorEmail: "siddhartha@example.com",
    },
    {
        id: "cl-106",
        title: "Lucide Icons Integration",
        description:
            "Integrating Lucide icons for scalable and customizable SVG icons in your projects.",
        slug: "lucide-icons-integration",
        category: "Design",
        tags: ["icons", "svg", "lucide"],
        installCommand: "npm i lucide-react",
        createdAt: "2026-05-05T12:00:00Z",
        authorClerkId: "user_5D88dd",
        authorEmail: "designer@example.com",
    },
    {
        id: "cl-107",
        title: "Shadcn UI Setup",
        description:
            "Beautifully designed components that you can copy and paste into your apps.",
        slug: "shadcn-ui-setup",
        category: "Design",
        tags: ["ui", "components", "radix"],
        installCommand: "npx shadcn-ui@latest init",
        createdAt: "2026-05-06T09:00:00Z",
        authorClerkId: "user_9Z22ee",
        authorEmail: "ui-expert@example.com",
    },
    {
        id: "cl-108",
        title: "Zustand State Management",
        description:
            "A small, fast, and scalable bearbones state-management solution.",
        slug: "zustand-state-management",
        category: "Frontend",
        tags: ["react", "state", "zustand"],
        installCommand: "npm i zustand",
        createdAt: "2026-05-07T15:20:00Z",
        authorClerkId: "user_3M11ff",
        authorEmail: "frontend-dev@example.com",
    },
    {
        id: "cl-109",
        title: "PostgreSQL with Neon",
        description:
            "Serverless Postgres with autoscaling and branching capabilities.",
        slug: "neon-postgres-setup",
        category: "Backend",
        tags: ["database", "sql", "neon"],
        installCommand: "npm i @neondatabase/serverless",
        createdAt: "2026-05-08T11:45:00Z",
        authorClerkId: "user_2H55rr",
        authorEmail: "data-architect@neon.tech",
    },
    // {
    //     id: "cl-110",
    //     title: "Vite Project Scaffolding",
    //     description:
    //         "Modern frontend tooling for faster development and optimized builds.",
    //     slug: "vite-project-scaffolding",
    //     category: "Frontend",
    //     tags: ["vite", "tooling", "frontend"],
    //     installCommand: "npm create vite@latest",
    //     createdAt: "2026-05-09T08:10:00Z",
    //     authorClerkId: "user_7L44gg",
    //     authorEmail: "build-master@example.com",
    // },
];
